/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ListDemo: typeof import('./components/ListDemo.vue')['default']
    ScrollComponent: typeof import('./components/ScrollComponent.vue')['default']
    SelectDemo: typeof import('./components/SelectDemo.vue')['default']
    SlidingBase: typeof import('./components/SlidingComponent/SlidingBase.vue')['default']
    SlidingComponent: typeof import('./components/SlidingComponent.vue')['default']
    SlidingList: typeof import('./components/SlidingComponent/SlidingList.vue')['default']
    SlidingMove: typeof import('./components/SlidingComponent/SlidingMove.vue')['default']
    SlidingX: typeof import('./components/SlidingComponent/SlidingX.vue')['default']
    Util: typeof import('./components/util')['default']
  }
}
